/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.DbConnection;
import java.sql.ResultSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.view.JasperViewer;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.PreparedStatement;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.design.JasperDesign;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashMap;
import java.awt.BorderLayout;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import javax.swing.JFrame;
import javax.swing.JScrollPane;


/**
 *
 * @author Hp
 */
public class Reports extends javax.swing.JFrame {

    JasperViewerFrame jasperViewerFrame = new JasperViewerFrame();
    /**
     * Creates new form Reports
     */
    public Reports() {
        initComponents();
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        returnNav = new javax.swing.JLabel();
        logoutNav = new javax.swing.JLabel();
        carrNav = new javax.swing.JLabel();
        customerNav = new javax.swing.JLabel();
        rentNav = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ReturnHistoryBtn = new javax.swing.JButton();
        RentHistoryBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        returnNav.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        returnNav.setForeground(new java.awt.Color(74, 78, 105));
        returnNav.setText("Return Cars");
        returnNav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnNavMouseClicked(evt);
            }
        });

        logoutNav.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        logoutNav.setForeground(new java.awt.Color(74, 78, 105));
        logoutNav.setText("Log out");
        logoutNav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutNavMouseClicked(evt);
            }
        });

        carrNav.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        carrNav.setForeground(new java.awt.Color(74, 78, 105));
        carrNav.setText("Cars");
        carrNav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carrNavMouseClicked(evt);
            }
        });

        customerNav.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        customerNav.setForeground(new java.awt.Color(74, 78, 105));
        customerNav.setText("Customers");
        customerNav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerNavMouseClicked(evt);
            }
        });

        rentNav.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        rentNav.setForeground(new java.awt.Color(74, 78, 105));
        rentNav.setText("Rent Cars");
        rentNav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rentNavMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoutNav)
                    .addComponent(rentNav)
                    .addComponent(returnNav, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carrNav)
                    .addComponent(customerNav))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(carrNav)
                .addGap(18, 18, 18)
                .addComponent(customerNav)
                .addGap(18, 18, 18)
                .addComponent(rentNav)
                .addGap(18, 18, 18)
                .addComponent(returnNav)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 253, Short.MAX_VALUE)
                .addComponent(logoutNav)
                .addGap(22, 22, 22))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(74, 78, 105));
        jLabel3.setText("CAR RENTAL SYSTEM REPORTS");
        jLabel3.setFocusable(false);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(74, 78, 105));
        jLabel4.setText("CAR RENT HISTORY");
        jLabel4.setFocusable(false);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(74, 78, 105));
        jLabel5.setText("CAR RETURN HISTORY");
        jLabel5.setFocusable(false);

        ReturnHistoryBtn.setBackground(new java.awt.Color(150, 103, 224));
        ReturnHistoryBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ReturnHistoryBtn.setForeground(new java.awt.Color(255, 255, 255));
        ReturnHistoryBtn.setText("Genrate The Report");
        ReturnHistoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnHistoryBtnActionPerformed(evt);
            }
        });

        RentHistoryBtn.setBackground(new java.awt.Color(150, 103, 224));
        RentHistoryBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RentHistoryBtn.setForeground(new java.awt.Color(255, 255, 255));
        RentHistoryBtn.setText("Genrate The Report");
        RentHistoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RentHistoryBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ReturnHistoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RentHistoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(237, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(jLabel3)
                    .addContainerGap(271, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(RentHistoryBtn)
                .addGap(43, 43, 43)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(ReturnHistoryBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(595, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutNavMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutNavMouseClicked
        dispose();
        Login newForm = new Login();

        // Set the behavior of the new form
        newForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        // Display the new form
        newForm.pack();
        newForm.setVisible(true);
        // TODO add your handling code here:

    }//GEN-LAST:event_logoutNavMouseClicked

    private void carrNavMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carrNavMouseClicked
        dispose();
        Cars newForm = new Cars();

        // Set the behavior of the new form
        newForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        // Display the new form
        newForm.pack();
        newForm.setVisible(true);
        // TODO add your handling code here:

    }//GEN-LAST:event_carrNavMouseClicked

    private void customerNavMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerNavMouseClicked

        dispose();
        Customers newForm = new Customers();

        // Set the behavior of the new form
        newForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        // Display the new form
        newForm.pack();
        newForm.setVisible(true);
        // TODO add your handling code here:

    }//GEN-LAST:event_customerNavMouseClicked

    private void rentNavMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rentNavMouseClicked
        dispose();
        ReturnCars newForm = new ReturnCars();

        // Set the behavior of the new form (e.g., default close operation)
        newForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        // Display the new form
        newForm.pack();
        newForm.setVisible(true);
        // TODO add your handling code here:

    }//GEN-LAST:event_rentNavMouseClicked
    
    private void ReturnHistoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnHistoryBtnActionPerformed
             Connection connection;
try {
    connection = DbConnection.getConnection();

    try {
       
        // Load the JasperDesign from your JRXML file
        JasperDesign jasperDesign1 = JRXmlLoader.load("I:\\javaNet\\CarRentalSystemEAD\\src\\View\\returnHis.jrxml");

        // Create a query object and set the SQL query
        JRDesignQuery designQuery1 = new JRDesignQuery();
        designQuery1.setText("SELECT returnid,rentid,carreturnedDate,delay, fine, totalfee FROM returntable");

        // Set the query for the JasperDesign
        jasperDesign1.setQuery(designQuery1);

        // Compile the JasperReport
        JasperReport report1 = JasperCompileManager.compileReport(jasperDesign1);

        // Fill the report with data from the database
        JasperPrint print1 = JasperFillManager.fillReport(report1, null, connection);

        // Create an instance of your JasperViewerFrame
        

        // Display the report in the JasperViewerFrame
        jasperViewerFrame.displayReport(print1);
     

        // Show the JasperViewerFrame
        jasperViewerFrame.setVisible(true);
    } catch (JRException e) {
        // Handle any JasperReports exceptions
    }
} catch (SQLException ex) {
    Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
}

    }//GEN-LAST:event_ReturnHistoryBtnActionPerformed

    private void returnNavMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnNavMouseClicked
        dispose();
        ReturnCars newForm = new ReturnCars();

        // Set the behavior of the new form (e.g., default close operation)
        newForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        // Display the new form
        newForm.pack();
        newForm.setVisible(true);
        // TODO add your handling code here: 
// TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_returnNavMouseClicked

    private void RentHistoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RentHistoryBtnActionPerformed
         
                    Connection connection;
                         try {
                             connection = DbConnection.getConnection();


                 try {
                    JasperDesign jasperDesign2 = JRXmlLoader.load("I:\\javaNet\\CarRentalSystemEAD\\src\\View\\returnHis.jrxml");

        // Create a query object and set the SQL query for the second report
        JRDesignQuery designQuery2 = new JRDesignQuery();
        designQuery2.setText("SELECT returnid, rentid, carreturnedDate, delay, fine, totalfee FROM returntable");

        // Set the query for the second JasperDesign
        jasperDesign2.setQuery(designQuery2);

        // Compile the second JasperReport
        JasperReport report2 = JasperCompileManager.compileReport(jasperDesign2);

        // Fill the second report with data from the database
        JasperPrint print2 = JasperFillManager.fillReport(report2, null, connection);

        // Display the second report in the same JasperViewerFrame
     
        jasperViewerFrame.displayReport(print2);
        
         // Create an instance of your JasperViewerFrame
         

        // Show the JasperViewerFrame
        jasperViewerFrame.setVisible(true);
                 } catch (JRException e) {
                        // Handle any JasperReports exceptions

                 } finally {
                     // Close the database connection in a real application
                     try {
                         if (connection != null) {
                             connection.close();
                         }
                     } catch (SQLException e) {
                     }
                 }

                  } catch (SQLException ex) {
                             Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
                         }
    }//GEN-LAST:event_RentHistoryBtnActionPerformed

 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RentHistoryBtn;
    private javax.swing.JButton ReturnHistoryBtn;
    private javax.swing.JLabel carrNav;
    private javax.swing.JLabel customerNav;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logoutNav;
    private javax.swing.JLabel rentNav;
    private javax.swing.JLabel returnNav;
    // End of variables declaration//GEN-END:variables
}
